<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EntidadesPublicasBoliviaSeeder extends Seeder
{
    public function run(): void
    {
        // Limpiar entidades viejas de Bolivia antes de re-seedear
        DB::table('entidades_publicas')->where('pais_codigo', 'BO')->delete();

        // Fuente: https://www.gob.bo/entidades (645 entidades, 282 relevantes para PEP)
        // Excluidos: Gobiernos Autónomos Municipales (~363), sucursales departamentales
        // Formato: [nombre, sigla]
        $entidades = [
            // ── Ministerios (18) ─────────────────────────────────────────────
            ['Ministerio de la Presidencia', 'MIN-PRES'],
            ['Ministerio de Culturas, Descolonización y Despatriarcalización', 'MIN-CDD'],
            ['Ministerio de Defensa', 'MIN-DEF'],
            ['Ministerio de Desarrollo Productivo, Rural y Agua', 'MIN-DPRyA'],
            ['Ministerio de Desarrollo Rural y Tierras', 'MIN-DRT'],
            ['Ministerio de Economía y Finanzas Públicas', 'MIN-EFP'],
            ['Ministerio de Educación', 'MIN-EDU'],
            ['Ministerio de Gobierno', 'MIN-GOB'],
            ['Ministerio de Hidrocarburos y Energías', 'MIN-HE'],
            ['Ministerio de Justicia y Transparencia Institucional', 'MIN-JTI'],
            ['Ministerio de Medio Ambiente y Agua', 'MIN-MAA'],
            ['Ministerio de Minería y Metalurgia', 'MIN-MM'],
            ['Ministerio de Obras Públicas, Servicios y Vivienda', 'MIN-OPSV'],
            ['Ministerio de Planificación del Desarrollo', 'MIN-PD'],
            ['Ministerio de Relaciones Exteriores', 'MIN-RREE'],
            ['Ministerio de Salud y Deportes', 'MIN-SD'],
            ['Ministerio de Trabajo, Empleo y Previsión Social', 'MIN-TEPS'],
            ['Ministerio Público', 'MINPUB'],

            // ── Órganos del Estado (12) ──────────────────────────────────────
            ['Vicepresidencia del Estado Plurinacional', 'VPEP'],
            ['Asamblea Legislativa Plurinacional', 'ALP'],
            ['Cámara de Diputados', 'CD'],
            ['Cámara de Senadores', 'CS'],
            ['Tribunal Constitucional Plurinacional', 'TCP'],
            ['Tribunal Supremo de Justicia', 'TSJ'],
            ['Consejo de la Magistratura', 'CM'],
            ['Órgano Electoral Plurinacional', 'OEP'],
            ['Órgano Judicial', 'OJ'],
            ['Contraloría General del Estado', 'CGE'],
            ['Defensoría del Pueblo', 'DP'],
            ['Procuraduría General del Estado', 'PROGE'],

            // ── Gobiernos Departamentales y Regionales (14) ──────────────────
            ['Gobierno Autónomo Departamental de Chuquisaca', 'GAD-CHU'],
            ['Gobierno Autónomo Departamental de Cochabamba', 'GAD-CBB'],
            ['Gobierno Autónomo Departamental de La Paz', 'GAD-LPZ'],
            ['Gobierno Autónomo Departamental de Oruro', 'GAD-ORU'],
            ['Gobierno Autónomo Departamental de Pando', 'GAD-PAN'],
            ['Gobierno Autónomo Departamental de Potosí', 'GAD-PTS'],
            ['Gobierno Autónomo Departamental de Santa Cruz', 'GAD-SCZ'],
            ['Gobierno Autónomo Departamental de Tarija', 'GAD-TAR'],
            ['Gobierno Autónomo Departamental del Beni', 'GAD-BEN'],
            ['Gobierno Autónomo Regional del Gran Chaco', 'GAR-GCH'],
            ['Gobierno Autónomo Indígena Guaraní Kereimba Iyaambae', 'GKI'],
            ['Gobierno Autónomo Indígena Originario Campesino de Salinas', 'GAIOC-SA'],
            ['Gobierno Autónomo Indígena Originario Campesino de Raqaypampa', 'GAIOC-TRP'],
            ['Gobierno Autónomo Indígena Originario Campesino del Jatún Ayllu Yura', 'GAIOC-AOJAY'],

            // ── Agencias y Autoridades (22) ──────────────────────────────────
            ['Agencia Boliviana de Energía Nuclear', 'ABEN'],
            ['Agencia Boliviana Espacial', 'ABE'],
            ['Agencia Boliviana de Correos', 'COBOL'],
            ['Agencia de Gobierno Electrónico y Tecnologías de Información y Comunicación', 'AGETIC'],
            ['Agencia de Infraestructura en Salud y Equipamiento Médico', 'AISEM'],
            ['Agencia del Desarrollo del Cine y Audiovisual Bolivianos', 'ADECINE'],
            ['Agencia Estatal de Medicamentos y Tecnologías en Salud', 'AGEMED'],
            ['Agencia Estatal de Vivienda', 'AEVIVIENDA'],
            ['Agencia Nacional de Hidrocarburos', 'ANH'],
            ['Autoridad de Fiscalización y Control Social de Agua Potable y Saneamiento Básico', 'AAPS'],
            ['Autoridad de Fiscalización y Control Social de Bosques y Tierras', 'ABT'],
            ['Autoridad de Fiscalización de Electricidad y Tecnología Nuclear', 'AETN'],
            ['Autoridad de Fiscalización de Empresas', 'AEMP'],
            ['Autoridad de Fiscalización del Juego', 'AJ'],
            ['Autoridad de Fiscalización y Control de Cooperativas', 'AFCOOP'],
            ['Autoridad de Fiscalización y Control de Pensiones y Seguros', 'APS'],
            ['Autoridad de Impugnación Tributaria', 'AIT'],
            ['Autoridad de Regulación y Fiscalización de Telecomunicaciones y Transportes', 'ATT'],
            ['Autoridad de Supervisión de la Seguridad Social de Corto Plazo', 'ASUSS'],
            ['Autoridad de Supervisión del Sistema Financiero', 'ASFI'],
            ['Autoridad Jurisdiccional Administrativa Minera', 'AJAM'],
            ['Autoridad Plurinacional de la Madre Tierra', 'APMT'],

            // ── Empresas Estatales (52) ──────────────────────────────────────
            ['Yacimientos Petrolíferos Fiscales Bolivianos', 'YPFB'],
            ['Empresa Nacional de Electricidad', 'ENDE'],
            ['Empresa Nacional de Telecomunicaciones', 'ENTEL'],
            ['Corporación Minera de Bolivia', 'COMIBOL'],
            ['Boliviana de Aviación', 'BOA'],
            ['Bolivia TV', 'BTV'],
            ['Empresa Boliviana de Alimentos y Derivados', 'EBA'],
            ['Empresa Boliviana de Industrialización de Hidrocarburos', 'EBIH'],
            ['Empresa Boliviana de Producción Agropecuaria', 'B-Agro'],
            ['Empresa Metalúrgica VINTO', 'VINTO'],
            ['Empresa Siderúrgica del Mutún', 'ES-MUTUN'],
            ['Empresa Azucarera San Buenaventura', 'EASBA'],
            ['Empresa de Apoyo a la Producción de Alimentos', 'EMAPA'],
            ['Empresa Estatal de Transporte por Cable Mi Teleférico', 'MT'],
            ['Empresa Estratégica Boliviana de Construcción y Conservación de Infraestructura Civil', 'EBC'],
            ['Empresa Misicuni', 'MISICUNI'],
            ['Empresa Nacional de Ferrocarriles', 'ENFE'],
            ['Empresa Naviera Boliviana', 'ENABOL'],
            ['Empresa Pública Nacional Estratégica Cartones de Bolivia', 'CARTONBOL'],
            ['Empresa Pública Nacional Estratégica Cementos de Bolivia', 'ECEBOL'],
            ['Empresa Pública Nacional Estratégica Papeles de Bolivia', 'PAPELBOL'],
            ['Empresa Pública Nacional Estratégica de Yacimientos de Litio Bolivianos', 'YLB'],
            ['Empresa Pública Transporte Aéreo Militar', 'TAM'],
            ['Empresa Pública QUIPUS', 'QUIPUS'],
            ['Empresa Pública YACANA', 'YACANA'],
            ['Empresa Pública Editorial del Estado Plurinacional de Bolivia', 'EDITORIAL'],
            ['Empresa Servicios Aéreos Bolivianos', 'ESABOL'],
            ['Empresa Tarijeña del Gas', 'EMTAGAS'],
            ['Empresa Local de Agua Potable y Alcantarillado Sucre', 'ELAPAS'],
            ['Empresa Pública Departamental de Servicios Eléctricos Tarija', 'SETAR'],
            ['Empresa Pública Departamental Estratégica de Aguas La Paz', 'EDALP'],
            ['Navegación Aérea y Aeropuertos Bolivianos', 'NAABOL'],
            ['Transportes Aéreos Bolivianos', 'TAB'],
            ['Vías Bolivia', 'VOBO'],
            ['Operadora del Tren Metropolitano de Cochabamba', 'MI TREN'],
            ['Oficina Técnica para el Fortalecimiento de la Empresa Pública', 'OFEP'],
            ['Servicio de Desarrollo de las Empresas Públicas Productivas', 'SEDEM'],
            ['Insumos Bolivia', 'IN-BOL'],
            ['PRO BOLIVIA', 'PRO-BOLIVIA'],

            // ── Entidades Financieras (15) ───────────────────────────────────
            ['Banco Central de Bolivia', 'BCB'],
            ['Banco de Desarrollo Productivo', 'BDP'],
            ['Banco Unión', 'BUN'],
            ['Fondo de Desarrollo del Sistema Financiero y Apoyo al Sector Productivo', 'FONDESIF'],
            ['Fondo Nacional de Desarrollo Regional', 'FNDR'],
            ['Fondo Nacional de Desarrollo Forestal', 'FONABOSQUE'],
            ['Fondo Nacional de Desarrollo Integral', 'FONADIN'],
            ['Fondo Nacional de Inversión Productiva y Social', 'FPS'],
            ['Fondo de Apoyo a la Reactivación de la Minería Chica', 'FAREMIN'],
            ['Fondo de Financiamiento para la Minería', 'FOFIM'],
            ['Fondo de Desarrollo Indígena', 'FDI'],
            ['Fondo Rotatorio de Fomento Productivo Regional', 'FRFPR'],
            ['Fondo de Solidaridad', 'FNSE'],
            ['Gestora Pública de la Seguridad Social de Largo Plazo', 'GESTORA'],
            ['Fundación Cultural del Banco Central de Bolivia', 'FC-BCB'],

            // ── Servicios Nacionales y Plurinacionales (34) ──────────────────
            ['Servicio de Impuestos Nacionales', 'SIN'],
            ['Servicio General de Identificación Personal', 'SEGIP'],
            ['Servicio General de Licencias de Conducir', 'SEGELIC'],
            ['Servicio Nacional de Sanidad Agropecuaria e Inocuidad Alimentaria', 'SENASAG'],
            ['Servicio Nacional de Áreas Protegidas', 'SERNAP'],
            ['Servicio Nacional de Patrimonio del Estado', 'SENAPE'],
            ['Servicio Nacional de Propiedad Intelectual', 'SENAPI'],
            ['Servicio Nacional de Riego', 'SENARI'],
            ['Servicio Nacional de Verificación de Exportaciones', 'SENAVEX'],
            ['Servicio Nacional del Sistema de Reparto', 'SENASIR'],
            ['Servicio Nacional Textil', 'SENATEX'],
            ['Servicio Nacional de Aerofotogrametría', 'SNAF'],
            ['Servicio Nacional de Hidrografía Naval', 'SNHN'],
            ['Servicio Nacional de Meteorología e Hidrología', 'SENAMHI'],
            ['Servicio Nacional de Registro y Control de Comercialización de Minerales y Metales', 'SENARECOM'],
            ['Servicio Nacional para la Sostenibilidad en Saneamiento Básico', 'SENASBA'],
            ['Servicio Estatal de Autonomías', 'SEA'],
            ['Servicio Geodésico de Mapas', 'SE-GEOMAP'],
            ['Servicio Geológico Minero', 'SERGEOMIN'],
            ['Servicio al Mejoramiento de la Navegación Amazónica', 'SEMENA'],
            ['Servicio Plurinacional de Asistencia a la Víctima', 'SEPDAVI'],
            ['Servicio Plurinacional de Defensa Pública', 'SEPDEP'],
            ['Servicio Plurinacional de Registro de Comercio', 'SEPREC'],
            ['Servicio Plurinacional de la Mujer y de la Despatriarcalización', 'SEPMUD'],
            ['Servicio de Encauzamiento de Ríos', 'SEARPI'],
            ['Dirección Nacional Servicio de Registro Cívico', 'SERECI'],
            ['Dirección General de Aeronáutica Civil', 'DGAC'],
            ['Dirección General de Migración', 'DIGEMIG'],
            ['Dirección General de la Fuerza Especial de Lucha Contra el Narcotráfico', 'FELCN'],
            ['Dirección del Notariado Plurinacional', 'DIRNOPLU'],
            ['Administración de Servicios Portuarios Bolivia', 'ASP-B'],
            ['Administradora Boliviana de Carreteras', 'ABC'],
            ['Aduana Nacional', 'AN'],
            ['Registro Único para la Administración Tributaria Municipal', 'RUAT'],

            // ── Fuerzas de Seguridad y Defensa (7) ──────────────────────────
            ['Comando General de la Policía', 'CGP'],
            ['Corporación de las Fuerzas Armadas para el Desarrollo Nacional', 'COFADENA'],
            ['Corporación del Seguro Social Militar', 'COSSMIL'],
            ['Consejo Nacional de Vivienda Policial', 'COVIPOL'],
            ['Consejo Supremo de Defensa Plurinacional', 'COSDEP'],
            ['Mutual de Servicios al Policía', 'MUSERPOL'],
            ['Dirección de Apoyo a la Prevención del Consumo de Drogas', 'DIPREVCON'],

            // ── Universidades Públicas (15) ──────────────────────────────────
            ['Universidad Mayor de San Andrés', 'UMSA'],
            ['Universidad Mayor de San Simón', 'UMSS'],
            ['Universidad Autónoma Gabriel René Moreno', 'UAGRM'],
            ['Universidad Autónoma Tomás Frías', 'UATF'],
            ['Universidad Técnica de Oruro', 'UTO'],
            ['Universidad Autónoma del Beni José Ballivián', 'UAB'],
            ['Universidad Amazónica de Pando', 'UAP'],
            ['Universidad Mayor Real y Pontificia de San Francisco Xavier', 'UMSFX'],
            ['Universidad Pública de El Alto', 'UPEA'],
            ['Universidad Nacional Siglo XX', 'UNSXX'],
            ['Universidad Autónoma Juan Misael Saracho', 'UAJMS'],
            ['Universidad Indígena Boliviana Comunitaria Intercultural Productiva Apiaguaiki Tüpa', 'UNIBOL-AT'],
            ['Universidad Indígena Boliviana Comunitaria Intercultural Productiva Casimiro Huanca', 'UNIBOL-CH'],
            ['Universidad Indígena Boliviana Comunitaria Intercultural Productiva Tupak Katari', 'UNIBOL-TK'],
            ['Comité Ejecutivo de la Universidad Boliviana', 'CEUB'],

            // ── Salud y Seguridad Social (15) ────────────────────────────────
            ['Caja Nacional de Salud', 'CNS'],
            ['Caja Petrolera de Salud', 'CPS'],
            ['Caja Bancaria Estatal de Salud', 'CBES'],
            ['Caja de Salud CORDES', 'CORDES'],
            ['Caja de Salud del Servicio Nacional de Caminos y Ramas Anexas', 'CSSNCRA'],
            ['Central de Abastecimiento y Suministros de Salud', 'CEASS'],
            ['Seguro Integral de Salud', 'SINEC'],
            ['Seguro y Reaseguros Personales UNIVIda', 'UNIVIda'],
            ['Instituto Nacional de Seguros de Salud', 'INASES'],
            ['Instituto Nacional de Laboratorios de Salud', 'INLASA'],
            ['Instituto Nacional de Salud Ocupacional', 'INSO'],
            ['Instituto del Seguro Agrario', 'INSA'],
            ['Gestora del Sistema de Acceso a la Justicia y Registro Público de la Abogacía', 'SAJ-RPA'],
            ['Escuela Nacional de Salud Pública', 'ENSP'],
            ['Unidad de Coordinación y Desarrollo del Sistema Único de Salud', 'SUIS'],

            // ── Institutos y Centros (15) ────────────────────────────────────
            ['Instituto Nacional de Estadística', 'INE'],
            ['Instituto Nacional de Reforma Agraria', 'INRA'],
            ['Instituto Nacional de Innovación Agropecuaria y Forestal', 'INIAF'],
            ['Instituto Boliviano de Metrología', 'IBMETRO'],
            ['Instituto Boliviano de la Ceguera', 'IBC'],
            ['Instituto Plurinacional de Estudio de Lenguas y Culturas', 'IPELC'],
            ['Academia Nacional de Ciencias', 'ANC'],
            ['Centro Nacional de Enfermedades Tropicales', 'CENETROP'],
            ['Centro de Investigación Agrícola Tropical', 'CIAT'],
            ['Centro Internacional de la Quinua', 'CIQ'],
            ['Centro de Investigaciones Arqueológicas, Antropológicas y Administración de Tiwanaku', 'CIAAAT'],
            ['Observatorio Plurinacional de la Calidad Educativa', 'OPCE'],
            ['Museo Nacional de Historia Natural', 'MNHN'],
            ['Unidad de Análisis de Políticas Sociales y Económicas', 'UDAPE'],
            ['Unidad de Investigaciones Financieras', 'UIF'],

            // ── Educación Departamental (9) ──────────────────────────────────
            ['Dirección Departamental de Educación Chuquisaca', 'DDE-CHU'],
            ['Dirección Departamental de Educación La Paz', 'DDE-LPZ'],
            ['Dirección Departamental de Educación Cochabamba', 'DDE-CBB'],
            ['Dirección Departamental de Educación Oruro', 'DDE-ORU'],
            ['Dirección Departamental de Educación Potosí', 'DDE-PTS'],
            ['Dirección Departamental de Educación Tarija', 'DDE-TAR'],
            ['Dirección Departamental de Educación Santa Cruz', 'DDE-SCZ'],
            ['Dirección Departamental de Educación Beni', 'DDE-BEN'],
            ['Dirección Departamental de Educación Pando', 'DDE-PAN'],

            // ── Otras Entidades (26) ─────────────────────────────────────────
            ['Escuela de Gestión Pública Plurinacional', 'EGPP'],
            ['Escuela de Jueces del Estado', 'EJE'],
            ['Escuela Militar de Ingeniería', 'EMI'],
            ['Escuela Boliviana Intercultural de Danza', 'EBID'],
            ['Escuela Boliviana Intercultural de Música', 'EBIM'],
            ['Conservatorio Plurinacional de Música', 'COPLUMU'],
            ['Orquesta Sinfónica Nacional', 'OSN'],
            ['Gaceta Oficial Bolivia', 'GACETA'],
            ['Lotería Nacional de Beneficencia y Salubridad', 'LONABOL'],
            ['Comité Nacional de la Persona con Discapacidad', 'CONALPEDIS'],
            ['Federación de Asociaciones Municipales de Bolivia', 'FAM'],
            ['Depósitos Aduaneros Bolivianos', 'DAB'],
            ['Complejo Agroindustrial Buena Vista', 'CABV'],
            ['Institución Pública Desconcentrada de Pesca y Acuicultura', 'PACU'],
            ['Entidad Ejecutora de Medio Ambiente y Agua', 'EMAGUA'],
            ['Entidad Ejecutora de Conversión a Gas Natural Vehicular', 'EEC-GNV'],
            ['Entidad Pública Desconcentrada Soberanía Alimentaria', 'IPDSA'],
            ['Oficina Técnica Nacional de los Ríos Pilcomayo y Bermejo', 'OTNR-PB'],
            ['Zona Franca Comercial e Industrial de Cobija', 'ZOFRACOBIJA'],
            ['Proyecto Sucre Ciudad Universitaria', 'PSCU'],
            ['Registro Internacional Boliviano de Buques', 'RIBB'],
            ['Centro de Comunicaciones La Paz', 'CCLP'],
            ['Unidad de Coordinación de Programas y Proyectos', 'UCPP'],
            ['Unidad de Proyectos Especiales', 'UPRE'],
            ['Unidad Operativa Boliviana', 'UOB'],
            ['Administración Autónoma para Obras Sanitarias Potosí', 'AAPOS'],
        ];

        $now = now();

        foreach ($entidades as [$nombre, $sigla]) {
            DB::table('entidades_publicas')->insert([
                'pais_codigo' => 'BO',
                'nombre' => $nombre,
                'sigla' => $sigla,
                'activo' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }
}
